### ISSUE TITLE
more banner art should be added to various commands

### ISSUE THREAD

**Issue by MaksiRose** [MaksiRose/paw-and-paper#193]
eg a map of the pack for rp go, or visuals for rp explore etc.
maybe its possible to make basic backgrounds and layer pictures of various animals that are created on the spot with node-canvas.

**Comment by MaksiRose** [comment]
Players that are involved in the command cannot be shown in the pictures (both the one doing the command and possibly mentioned players) because of the different types of species.

- [ ] the packs map for the `go` command
- [ ] picture of the lake or similar for the `drink` command
- [ ] for `quest` command:
  - [ ] Youngling quest
  - [ ] Apprentice quests:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] Hunter/Healer quests:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] Elderly quests:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
- [ ] picture of the sleeping dens or similar for the `rest` command
- [ ] picture of the food den or similar for the `store` command
- [ ] maybe show inventory in form of a picture that updates itself?
- [ ] for the `water` command:
  - [ ] underwatered
  - [ ] barely watered but still good
  - [ ] perfectly watered
  - [ ] overwatered
- [ ] picture of the ruins or similar for the `share` command
- [ ] for the `explore` command:
  - [ ] finding a ginkgo sapling:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] finding nothing:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] finding a human camp:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] finding a plant:
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome
  - [ ] finding an enemy (but the enemy can't be really seen, maybe shadow or something):
    - [ ] cold biome
    - [ ] warm biome
    - [ ] water biome

**Comment by MaksiRose** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
